version: "2.4"

services:
  nginx:
    build: nginx/
    links:
      - php-fpm

  php-fpm:
    build: php-fpm/
    volumes:
      - .:/var/www/html
    links:
      - redis
      - pushgateway
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis

  pushgateway:
    image: prom/pushgateway

  phpunit:
    build: php-fpm/
    volumes:
      - .:/var/www/html
    links:
      - redis
      - pushgateway
      - nginx
    environment:
      - REDIS_HOST=redis
